---
##########################################################################################################
## bond-config:
##
## Configure the physical and sub-interfaces behind the bond
##########################################################################################################
- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu_16.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release != 'bionic'

- include: ubuntu_18.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == 'bionic'
